[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stardust-tools"
version = "0.2.0"
description = "General tools and enhancements for Python."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Grant Giesbrecht", email = "giesbrechtgrant@gmail.com" }]
dependencies = [
    "h5py>=3.0",
    "colorama>=0.4",
    "cryptography>=3.4",
    "matplotlib>=3.5",
    "numpy>=1.22",
    "pylogfile>=0.5.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering"
]
license = "BSD-2-Clause"

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.setuptools]
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/Grant-Giesbrecht/stardust"
Issues = "https://github.com/Grant-Giesbrecht/stardust/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
